#!/bin/bash
# Get current song information and status

# Base16 google dark - green and red
red="#f96a38"
green="#198844"

stat=$(mpc status)
current=$(echo "$stat" |
	awk 'FNR == 1 { SONG = $0 } FNR == 2 { print SONG,$2,$3,$4 }')
paused=$(echo "$stat" | awk 'FNR == 2 { print $1 }')

echo $current
echo ""

if [[ $paused == "[paused]" ]]; then
	printf $red
else
	printf $green
fi

