#!/bin/bash

if [[ $(pamixer --get-mute) = "false" ]]; then
	volume=$(pamixer --get-volume | awk '{print $1}')
	
	if [[ $volume -le 33 ]]; then
		printf "🔈 %d%%" $volume
	elif [[ $volume -le 66 ]]; then
		printf "🔉 %d%%" $volume
	else
		printf "🔊 %d%%" $volume
	fi
else
	echo "🔇"
fi

