# https://github.com/greshake/i3status-rust/blob/master/blocks.md

icons="awesome"

# vi:syntax=toml

# base16-i3status-rust (https://github.com/mystfox/base16-i3status-rust)
# Default Dark by Chris Kempson (http://chriskempson.com)

[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#181818"
idle_fg = "#d8d8d8"
info_bg = "#86c1b9"
info_fg = "#181818"
good_bg = "#a1b56c"
good_fg = "#181818"
warning_bg = "#f7ca88"
warning_fg = "#181818"
critical_bg = "#ab4642"
critical_fg = "#181818"
# The rest of the theme settings are left at default.
separator = "|"
separator_bg = "#181818"
separator_fg = "#ffffff"


[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60

[[block]]
block = "memory"
format_mem = "{Mum}MB/{MTm}MB({Mup}%)"
format_swap = "{SUm}MB/{STm}MB({SUp}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "net"
device = "enp3s0"
ssid = true
ip = true
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "US/Central"
interval = 60

[[block]]
block = "sound"
